Add missing inspect import
Without inspect import, parsing will fail:

```
Traceback (most recent call last):
  File "/home/tom/ow/./ow", line 408, in <module>
    isCollectionOrExit(folderWithPhotosUrl)
  File "/home/tom/ow/./ow", line 147, in isCollectionOrExit
    prettyOutputFilename = captureXmlResponse(response.text)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/ow/./ow", line 112, in captureXmlResponse
    caller = inspect.stack()[1][3]
             ^^^^^^^
NameError: name 'inspect' is not defined
```